name: main

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: apt-get update
    - run: apt-get install -y flex bison libbison-dev
    - run: make
